name: dbt_snowflake_rap_enforcement_integration_tests
version: 0.1.0
config-version: 2

profile: integration_tests

on-run-start:
  - "{{ dbt_snowflake_rap_enforcement.check_downstream_row_access_policy() }}"

vars:
  row_access_policy_enforcement:
    exclude_resource_types: ["test", "analysis"]
    enforced_materializations:
      - table
      - incremental
      - snapshot
      - dynamic_table
    optional_materializations:
      - view
      - ephemeral
    unknown_materialization: error
    authoritative: true

models:
  dbt_snowflake_rap_enforcement_integration_tests:
    +schema: main
