{% macro run_unit_tests() %}
  {% do test_parse_row_access_policy() %}
  {% do test_plan_relation_row_access_policy() %}
  {% do test_plan_row_access_policy_alters() %}
  {% do test_plan_authoritative_replace_alter() %}
  {% do test_plan_drop_when_config_cleared() %}
  {% do test_alter_row_access_policy_sql() %}
  {% do test_format_policy_fqn_sql_uppercases_unquoted() %}
  {% do test_ref_entity_domain_for_materialized() %}
  {% do test_build_policy_references_sql() %}
  {% do test_build_policy_references_by_policy_sql() %}
  {% do test_chunk_list_and_policy_reference_batches() %}
  {% do test_normalize_ref_arg_column_names() %}
  {% do test_resolve_apply_target_node_ids() %}
  {% do test_build_existing_relations_sql() %}
  {% do test_index_helpers_and_missing_plan() %}
  {% do test_plan_noop_when_columns_from_ref_arg_column_names() %}
  {% do test_hybrid_policy_inventory_selection() %}
  {% do test_choose_policy_reference_inventory_strategy() %}
  {% do test_collect_target_database_names_and_policy_sql() %}
  {% do test_unique_policy_lookup_call_count() %}
  {% do test_select_existing_relation_inventory_targets() %}
  {% do test_partition_and_group_attachment_maps() %}
  {% do test_relation_inventory_chunking() %}
  {% do test_format_apply_inventory_metrics() %}
  {% do test_relation_inventory_planner_semantics() %}
  {% do test_node_satisfies_requirement() %}
  {% do test_get_downstream_requirement_explicit() %}
  {% do test_matches_allow_without_row_access_policy() %}
  {% do test_collect_downstream_row_access_policy_boundary() %}
  {% do test_global_meta_enforcement_use_cases() %}
  {% do test_downstream_adjacency_discovery_order() %}
  {% do test_downstream_direct_unprotected_terminal() %}
  {% do test_downstream_sibling_manifest_order() %}
  {% do test_downstream_passthrough_chain() %}
  {% do test_downstream_diamond_dedup() %}
  {% do test_downstream_rap_boundary_and_existing_cases() %}
  {% do test_downstream_excluded_and_mixed_resources() %}
  {% do test_downstream_requirement_modes() %}
  {% do test_downstream_allow_rules() %}
  {% do test_downstream_passthrough_cycle() %}
  {% do test_downstream_node_facts_and_metrics_format() %}
  {% do test_downstream_scale_downscaled_matches_legacy() %}
  {% do test_downstream_shared_tail_matches_legacy() %}
  {% do test_downstream_shared_tail_complexity() %}
  {% do test_downstream_scale_N15000_R6000_complexity() %}

  {{ log("All dbt-snowflake-rap-enforcement unit tests passed.", info=true) }}
{% endmacro %}
